// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwuhodoqsclsnnnbsiun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3dWhvZG9xc2Nsc25ubmJzaXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDU5MDQsImV4cCI6MjA3MDQ4MTkwNH0.A1bskTAMWLImjIV0HChILF2R2wJU69yA5UEvwTRabCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});